---
title: "A5 -- Routing"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This assignment will have you do a little machine learning.  Giving historical airplane on time performance data, you will offer suggestions for two-hop flights that minimize the chance of missing a connection.

## Fine print: 
  * Input:   A list of tuples of Year, Month, Day, Origin, Destination (e.g. 2001, 09, 11, DEN, DCA)  where Year is the same for all tuples
  * Ouput:   a list of proposed flights (e.g.  [(2001,09,11, 1256, 1222, UA, DEN, ORD),(2001,09,11,1910,UA, ORD, DCA)])
  * Scoring: 1 point per flight if the flight arrives on time at the destination, -100 per proposed flight that does not arrive on time or is cancelled
  * You can use data form previous years to build a model of flight delays, you are not allowed to use data from the Year requested in the model
  * Do not return direct flights
  * Connections must have at least 45 minutes between landing and takeoff, and no more than 12 hours
 *  The PDF report file should include details about the implementation as well as a study of the performance and accuracy of the solution. A detailed breakdown of what each team member worked should be added. Grading will include the quality of the report. All projects will be code walked.
